name: Create Lineage 20 TD Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Deletes
      run: |
       df -h
       sudo apt-get purge -y '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell microsoft-edge-stable mono-devel 
       sudo apt-get autoremove -y
       sudo apt-get clean
       sudo rm -rf /var/lib/apt/lists/* 
       sudo rm -rf /opt/hostedtoolcache
       sudo rm -rf /usr/local/games
       sudo rm -rf /usr/local/sqlpackage
       sudo rm -rf /usr/local/.ghcup
       sudo rm -rf /usr/local/share/powershell
       sudo rm -rf /usr/local/share/edge_driver
       sudo rm -rf /usr/local/share/gecko_driver
       sudo rm -rf /usr/local/share/chromium
       sudo rm -rf /usr/local/share/chromedriver-linux64
       sudo rm -rf /usr/local/share/vcpkg
       sudo rm -rf /usr/local/lib/python3.10
       sudo rm -rf /usr/local/lib/node_modules
       sudo rm -rf /usr/local/julia1.9.4
       sudo rm -rf /opt/mssql-tools

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
         root-reserve-mb: 512
         swap-size-mb: 1024
         remove-android: 'true'
         remove-dotnet: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         remove-docker-images: 'true'
    - name: Show
      run: |
        #sudo du --max-depth=2 -h /opt/hostedtoolcache 2>/dev/null
        sudo du --max-depth=2 -h /usr/local 2>/dev/null
        sudo du --max-depth=2 -h /opt 2>/dev/null
        df -h

    - name: Exit
      run: exit 1

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run prerequisites
      uses: ./.github/actions/create-lineage-builder

    - name: Execute Action
      run: |
        cd $CheckoutDir/android/lineage
        git clone https://github.com/AndyCGYan/lineage_build_unified lineage_build_unified -b lineage-20-td
        git clone https://github.com/AndyCGYan/lineage_patches_unified lineage_patches_unified -b lineage-20-td
        bash lineage_build_unified/buildbot_unified.sh treble 64VS

    - name: Download of build-output
      uses: actions/download-artifact@v2
      with:
          name: build-output
          path: /root/build-output