name: Create Lineage 20 TD Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
         root-reserve-mb: 512
         swap-size-mb: 1024
         remove-android: 'true'
         remove-dotnet: 'true'
         remove-haskell: 'true'
         remove-codeql: 'true'
         remove-docker-images: 'true'
    
    - name: Deletes
      run: sudo rm -rf /opt/hostedtoolcache

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Run prerequisites
      uses: ./.github/actions/create-lineage-builder

    - name: Execute Action
      run: |
        cd $CheckoutDir/android/lineage
        git clone https://github.com/AndyCGYan/lineage_build_unified lineage_build_unified -b lineage-20-td
        git clone https://github.com/AndyCGYan/lineage_patches_unified lineage_patches_unified -b lineage-20-td
        bash lineage_build_unified/buildbot_unified.sh treble 64VS

    - name: Download of build-output
      uses: actions/download-artifact@v2
      with:
          name: build-output
          path: /root/build-output